"""empty message

Revision ID: 16ff8b1e8c8e
Revises: 600d8cedea1f
Create Date: 2016-05-11 16:57:47.762000

"""

# revision identifiers, used by Alembic.
revision = '16ff8b1e8c8e'
down_revision = '600d8cedea1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column('comments', sa.Column('body_html', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
