"""empty message

Revision ID: 2b62f28324c9
Revises: 667330514dbe
Create Date: 2016-04-26 20:20:39.241000

"""

# revision identifiers, used by Alembic.
revision = '2b62f28324c9'
down_revision = '667330514dbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.create_table('system',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###
