"""empty message

Revision ID: 504579eee369
Revises: 85ff95a38471
Create Date: 2016-05-02 14:31:43.270000

"""

# revision identifiers, used by Alembic.
revision = '504579eee369'
down_revision = '85ff95a38471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concern_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concern_posts')
    ### end Alembic commands ###
