"""empty message

Revision ID: 9aea9d802fb8
Revises: ee489efbf9c2
Create Date: 2016-04-30 20:34:16.654000

"""

# revision identifiers, used by Alembic.
revision = '9aea9d802fb8'
down_revision = 'ee489efbf9c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_avatar_url'), 'users', ['avatar_url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_avatar_url'), table_name='users')
    op.drop_column('users', 'avatar_url')
    ### end Alembic commands ###
