"""empty message

Revision ID: 9c75274fce1d
Revises: 07d57a9a0cd7
Create Date: 2016-05-10 21:52:49.449000

"""

# revision identifiers, used by Alembic.
revision = '9c75274fce1d'
down_revision = '07d57a9a0cd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('agree_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('disagree_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'disagree_count')
    op.drop_column('posts', 'agree_count')
    ### end Alembic commands ###
