"""empty message

Revision ID: b88893abad4d
Revises: 3040319d174a
Create Date: 2016-05-04 22:51:00.535000

"""

# revision identifiers, used by Alembic.
revision = 'b88893abad4d'
down_revision = '3040319d174a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('attitude', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remarks_comment_id'), 'remarks', ['comment_id'], unique=False)
    op.create_index(op.f('ix_remarks_owner_id'), 'remarks', ['owner_id'], unique=False)
    op.create_table('subcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('for_comment_id', sa.Integer(), nullable=True),
    sa.Column('from_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['for_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['from_comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomment_for_comment_id'), 'subcomment', ['for_comment_id'], unique=False)
    op.create_index(op.f('ix_subcomment_from_comment_id'), 'subcomment', ['from_comment_id'], unique=False)
    op.create_index(op.f('ix_subcomment_id'), 'subcomment', ['id'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_concern_posts_post_id'), 'concern_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_concern_posts_user_id'), 'concern_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_follows_followed_id'), 'follows', ['followed_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_id'), table_name='follows')
    op.drop_index(op.f('ix_concern_posts_user_id'), table_name='concern_posts')
    op.drop_index(op.f('ix_concern_posts_post_id'), table_name='concern_posts')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index(op.f('ix_subcomment_id'), table_name='subcomment')
    op.drop_index(op.f('ix_subcomment_from_comment_id'), table_name='subcomment')
    op.drop_index(op.f('ix_subcomment_for_comment_id'), table_name='subcomment')
    op.drop_table('subcomment')
    op.drop_index(op.f('ix_remarks_owner_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_comment_id'), table_name='remarks')
    op.drop_table('remarks')
    ### end Alembic commands ###
