"""empty message

Revision ID: dc69f9e4d3f8
Revises: 504579eee369
Create Date: 2016-05-02 14:45:16.068000

"""

# revision identifiers, used by Alembic.
revision = 'dc69f9e4d3f8'
down_revision = '504579eee369'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concern_posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concern_posts', 'timestamp')
    ### end Alembic commands ###
