"""empty message

Revision ID: dd27be1b93d7
Revises: 9aea9d802fb8
Create Date: 2016-05-01 17:45:17.803000

"""

# revision identifiers, used by Alembic.
revision = 'dd27be1b93d7'
down_revision = '9aea9d802fb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
