"""empty message

Revision ID: df5fe4b4136b
Revises: 6f0a6b979be9
Create Date: 2016-05-09 16:01:23.133000

"""

# revision identifiers, used by Alembic.
revision = 'df5fe4b4136b'
down_revision = '6f0a6b979be9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    ### end Alembic commands ###
