"""empty message

Revision ID: f0962b9ff590
Revises: 2b62f28324c9
Create Date: 2016-04-27 15:36:28.656000

"""

# revision identifiers, used by Alembic.
revision = 'f0962b9ff590'
down_revision = '2b62f28324c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permission')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
